# Generated by Django 5.2 on 2025-04-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckd_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ckdrecord',
            name='smoking',
        ),
    ]
